### PR TITLE
Fix compat

### LINKED ISSUE #94: `Distributions.jl` in compat section
I've recently bumped into a problem trying to install `GaussinMixtures.jl` together with a few other packages, because of strict `compat` section in `Project.toml`, in particular the constrains related to `Distributions.jl`. In my project `GaussianMixtures.jl` successfully coexists with `Distributions.jl@v0.25.16`. I suggest easing this constraint.

### PR DESCRIPTION
**Pull request by yuehhua**
Closed #94.

### CODE REVIEW

**Comment by yuehhua** [comment]
I got several deps updated and tests passed.

**Comment by yuehhua** [comment]
@davidavdav I added CI for this package. It will run all unit tests automatically. Now you can approve to trigger CI to start running.

**Comment by davidavdav** [comment]
Great, you found the bug with the matrix conversion.  I was stuck there as I couldn't find the culprit.

**Comment by yuehhua** [comment]
Then you can fire a patch release.

**Pull request merged**
