### PR TITLE
ScikitLearn.jl glue

### PR DESCRIPTION
**Pull request by cstjean**
This is the same code as in the other PR (though I clarified `density`), but as I've explained there, it's cleaner to have the code live in GaussianMixtures.jl, importing `ScikitLearnBase`. It avoids `@require`. I'm keeping the other PR open for now, so if you're not comfortable, I can just close this and merge the other one, no big deal. Thank you for the code review.

### CODE REVIEW

**Comment by davidavdav** [comment]
What is wrong about a @require?   This way you can remove the dependence on SciKitLearn, which breaks 0.3 compatibility.

**Comment by cstjean** [comment]
> What is wrong about `@require`?

As far as I know, it's currently broken on 0.5, though I assume it'll be fixed before release. Are you suggesting that we add `Requires.jl` to `REQUIRE`, and make `ScikitLearnBase` a conditional import? 

It wouldn't be hard to make `ScikitLearnBase` 0.3-compatible. I just checked and its only problem is with the forward declarations.

**Comment by davidavdav** [comment]
Yes, 

Well I don't know how heavy or stable ScikitLearn.jl is.  The PR provides support for ScikitLearn, but GaussianMixtures itself is not dependent on it.  So I though the idea is that if you say 

```
using GaussianMixtures
```

You don't get the additional baggage, but if you say

```
using GaussianMixtures
using ScikitLearn
```
you get the additional interface to ScikitLearn from GaussianMixtures.  I should actually do the same for Distributiions, although I might actually use something in random sampling, so I probably need that anyway.

**Comment by cstjean** [comment]
I'm sorry, I haven't been very clear in describing the setup, which is designed specifically to address the issue you raised. You're right that if `ScikitLearn.jl` was a single package, it would be inconvenient for GaussianMixtures.jl. That's why I split it into two parts: `ScikitLearn.jl` (which contains pipelines, feature-unions, hyperparameter tuning code, etc.) and `ScikitLearnBase.jl`. The latter is [just one very small file](https://github.com/cstjean/ScikitLearnBase.jl/blob/master/src/ScikitLearnBase.jl) and an empty REQUIRE.

In this PR, the scikitlearn.jl file has `import ScikitLearnBase`, but doesn't require `ScikitLearn.jl`. That way, `using GaussianMixtures` carries no extra baggage (well, except for the 50 lines of code in ScikitLearnBase), and users who want to use `ScikitLearn.jl` need to explicitly `Pkg.add` and `import` it.

I didn't anticipate that Julia 0.3 was still kicking around, but it's easy enough to fix in `ScikitLearnBase`. I'll do it today. It'll require tagging a new version, and should fix the Travis issue.

**Comment by cstjean** [comment]
All fixed, including Julia 0.3 support; the Travis error is unrelated (something in `test/train.jl`).

**Comment by cstjean** [comment]
Awesome, thanks!

**Pull request merged**
