### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by metab0t**

### CODE REVIEW

**Comment by davidavdav** [comment]
Hi, thanks. 

How does this patch pass the tests?  I don't see CI output in this PR

**Comment by metab0t** [comment]
I have tested it locally and tests work fine on my machine.
I don't know why CI is not triggered by this PR.

**Comment by davidavdav** [comment]
https://travis-ci.org/github/davidavdav/GaussianMixtures.jl after merge

**Comment by metab0t** [comment]
> 
> 
> https://travis-ci.org/github/davidavdav/GaussianMixtures.jl after merge

The stacktrace of Julia nightly seems weird.
The error happens in libuv functions.

**Comment by nalimilan** [comment]
Would it be possible to tag a new release? That would help for example https://github.com/cstjean/ScikitLearn.jl/pull/92.

**Comment by davidavdav** [comment]
@JuliaTagBot minor

**Comment by nalimilan** [comment]
Thanks, but I don't see any release in the General registry, and Project.toml still says 0.3.2. JuliaTagBot only creates tags, right?

(While you're at it, there are a few outstanding PRs bumping dependencies.)

**Comment by davidavdav** [comment]
I don't know.  I've tried to release by using github release https://github.com/davidavdav/GaussianMixtures.jl/releases/tag/v0.3.3 but maybe that is not the way to release. 

All the bots completely confuse me, the system keeps changing, and I have no idea how it currently works.  I am with this guy https://discourse.julialang.org/t/release-a-new-version-of-registered-packages-again/47765

**Comment by nalimilan** [comment]
Yes now you have to update Project.toml, and then add a comment to a commit (not a PR) saying `@JuliaRegistrator register`. JuliaTagBot only creates tags afterwards (but that's somewhat independent from actual releases). You probably have to enable JuliaRegistrator on the project.

**Comment by davidavdav** [comment]
Thanks, I hope it is done correctly now!

**Comment by ExpandingMan** [comment]
Hey guys, this never actually got tagged, can we tag this?

**Pull request merged**
