### PR TITLE
cleaned up tests

### PR DESCRIPTION
**Pull request by floswald**
* used `@testset` throughout
* use `@test` wherever possible
* updated package dependencies (hence Manifest.toml committed) to get rid of #40 
* used `RDatasets.dataset("datasets","faithful")` to have an *official* reference dataset (and associated known numerical results)

### CODE REVIEW

**Comment by floswald** [comment]
* pushed 2 more commits because my travis instance was unable to build HDF5 properly (JLD dependency)
* I moved away from JLD and to JLD2 in the next 2 commits. JLD2 is hdf5 compatible but pure julia. you see it interfaces with `FileIO`.

**Comment by davidavdav** [comment]
Thanks, 

I don't understand much of the new packaging system, but at some stage I learned that the Manifest.toml is actually not necessary in the repo.  What is your idea about this?

**Comment by floswald** [comment]
yes that's what I also thought. I am pretty sure though that the tests failed because of some old versions of packages (as soon as i did `] up` it passed). so if i commit a manifest, the package is nailed to a certain set of versions - if i don't the user has to figure out for themselves which exact version of each package is working here. i'm not totally sure this is best practice (I have a hunch its not! :smile: )

**Comment by davidavdav** [comment]
It sounds a bit like what npm does for javascript, there I believe every project has its own installed version; also the virtualenvs in python try to accomplish a similar thing.  The docs about the new packaging system were (are?) all about the hype of getting rid of the version hell, but unclear on how I need to upgrade an existing project and what is needed and what is no longer needed...

**Pull request merged**
